title: Simplify
description: Simplify is a set of .NET libraries that provide infrastructure for your applications. DI and mocking friendly.

baseurl: ""
url: "https://simplifynet.dev"
repository: "SimplifyNet/Simplify"
templates_repository_url: "https://github.com/SimplifyNet/Simplify.ProjectsTemplates"

simplify_web_url: "https://web.simplifynet.dev"

markdown: kramdown
theme: jekyll-theme-midnight